# Kafka con KRaft mode (sin Zookeeper)
kraft:
  enabled: true
  
# Configuraci贸n de listeners
listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
    
# Configuraci贸n del controller
controller:
  replicaCount: 1
  persistence:
    enabled: true
    size: 8Gi
    
# Configuraci贸n del broker
broker:
  replicaCount: 1
  persistence:
    enabled: true
    size: 20Gi
  resources:
    requests:
      memory: 2Gi
      cpu: 1000m
    limits:
      memory: 4Gi
      cpu: 2000m
      
# Configuraci贸n para desarrollo
metrics:
  kafka:
    enabled: true
  jmx:
    enabled: true
    
# Service
service:
  type: ClusterIP
  ports:
    client: 9092
